title: Azure Document Intelligence OCR Staging
description: This Add-On uses Azure's Document Intelligence API to OCR documents.
disclosures: |
  This Add-On uses a form of machine learning to perform OCR. The Add-On sends data to Microsoft using the Document Intelligence API. 
  You may read the document intelligence [privacy](https://learn.microsoft.com/en-us/azure/foundry/responsible-ai/document-intelligence/data-privacy-security) and training policy
  to determine how this data is handled.
instructions: ''
type: object
documents:
  - selected
properties: 
  to_tag:
    title: Tag OCR'd documents?
    type: boolean
    description: "If selected, the key/value pair of ocr_engine:azure will be added to the document as metadata"
categories: 
  - extraction
  - premium
# Acceptable categories are premium, ai, export, bulk, file,  monitor, statistical, and extraction. 
# You can read more about DocumentCloud Add-On categories here: https://www.documentcloud.org/help/add-ons#types-of-add-ons
cost:
  price: 1
  amount: 1
  unit: page
version: 2
